[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

# Must set evm version to paris since solc > 0.8.20 uses op code PUSH0
evm_version = "cancun"
optimizer_runs = 100
via_ir = false
revert_strings = "strip"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
base = "${BASE_MAINNET_RPC_URL}"
tenderly = "${TENDERLY_FORK_RPC_URL}"